OpenNMTBenchmark:
  Database:
    hosts:
      - host: localhost
        port: 27017
    replicaSet: null
    poolSize: 15
    mongoose:
      debug: false
    ssl: false
    sslValidate: false
    sslCA: null # array of files or file
    sslCert: null # file
    sslKey: null # file
    sslPass: null # file
    addUser: false # add user to db as admin
    User:
      login:
      password:
  default:
    LP: enfr
    metric: BLEU
    locale: en
  locales: ['en']
  datapath: ./data
  scorer_cli: ./scripts/multi-bleu.perl
  URL: http://www.opennmtbenchmark.com:3000
  passport:
    clientID: cdb6ff225507c68d0c4a
    clientSecret: d1a90e6ff3ea1f8bcedc504d64ea2664428fc97f
    callbackPath: /auth/github/callback
