OpenNMTBenchmark:
  Database:
    hosts:
      - host: localhost
        port: 27017
    replicaSet: null
    poolSize: 150
    mongoose:
      debug: false
    ssl: false
    sslValidate: false
    sslCA: null # array of files or file
    sslCert: null # file
    sslKey: null # file
    sslPass: null # file
    addUser: false # add user to db as admin
    User:
      login:
      password:
  default:
    LP: fres
    metric: BLEU
    locale: en
  locales: ['en']
  datapath: ./data
  scorer_cli: ./scripts/multi-bleu.perl
  env:
    dev:
      URL: http://www.opennmtbenchmark.com:3000
      passport:
        clientID: 8dee7589e42c31b7314f
        clientSecret: bb2c8f2c602f0c626debab6615d8dc9bb5b008db
        callbackPath: /auth/github/callback
    prod:
      URL: http://scorer.nmt-benchmark.net
      passport:
        clientID: 20f0778ece2352e6717c
        clientSecret: 72fad106821047127d23bd447e550bcfffd87bf0
        callbackPath: /auth/github/callback
